### ISSUE TITLE
Benchmarks out-of-date

### ISSUE THREAD

**Issue by jdelmerico** [julienschmidt/go-http-routing-benchmark#72] opened 2017-06-02 06:55 UTC
It's great that these benchmarks exist, but there should be a date associated with the running of the benchmark.  It would be even better if there was also some process that ran once in a while to update these.  It looks like the last run was more than a year old for some of the routers. 

Thanks for the great work with httprouter!

**Comment by julienschmidt** [comment] 2019-10-07 09:51
Duplicate of #4

**Closed by julienschmidt** 2019-10-07 09:51 UTC
