### ISSUE TITLE
new benchmark for these routing

### ISSUE THREAD

**Issue by asynchronoust** [julienschmidt/go-http-routing-benchmark#77] opened 2017-12-03 14:53 UTC
Hi, 

I find the benchmark for these routing codes is very old, the README.md file is commited four years ago

Is there new benchmark for these framework?  I believe these framework have done a lot of work to improve their performance

**Comment by julienschmidt** [comment] 2019-10-07 09:51
Duplicate of #4

**Closed by julienschmidt** 2019-10-07 09:51 UTC
